# Generated by Django 3.2.2 on 2021-05-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210511_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='claims/thumbnail'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='file',
            field=models.ImageField(upload_to='claims/'),
        ),
    ]
