# Generated by Django 3.2.2 on 2021-05-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210511_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='vitex_address',
            field=models.CharField(default='', max_length=56),
        ),
    ]
