# Generated by Django 3.2.2 on 2021-05-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_claim_vitex_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to='claims/thumbnail'),
        ),
    ]
