# Generated by Django 3.2.2 on 2021-05-12 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_claim_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('file', models.ImageField(upload_to='claims/')),
            ],
        ),
        migrations.RemoveField(
            model_name='claim',
            name='file',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('preparing', 'preparing'), ('submitted', 'submitted'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('updated', 'updated')], default='preparing', max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='telegram',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='claim',
            name='vitex_address',
            field=models.CharField(blank=True, default='', max_length=56),
        ),
        migrations.AddField(
            model_name='claim',
            name='files',
            field=models.ManyToManyField(to='app.ClaimFile'),
        ),
    ]
