# Generated by Django 3.2.2 on 2021-05-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210512_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimfile',
            name='id',
            field=models.UUIDField(default='<function now at 0x0000024ED9FA9160>', primary_key=True, serialize=False, unique=True),
        ),
    ]
